---
- name: disallow TCP connections
  iptables:
    table: filter
    chain: INPUT
    protocol: tcp
    source: "{{ docker_metrics_source }}"
    destination_port: "{{ docker_metrics_port }}"
    jump: ACCEPT
    state: absent
    comment: "from ansible"
    
- name: allow TCP connections
  iptables:
    table: filter
    chain: INPUT
    protocol: tcp
    destination_port: "{{ docker_metrics_port }}"
    jump: ACCEPT
    comment: "from ansible"
    
