---
- name: ensure that the users exist and the ssh keys are generated
  user:
    name: "{{ backup_user }}"
    generate_ssh_key: yes
    ssh_key_bits: "{{ backup_user_ssh_key_bits }}"
    ssh_key_comment: "backup"

- name: save the public keys (root user)
  fetch:
    src: /root/.ssh/id_rsa.pub
    dest: keys/users/backup/
    flat: yes
  when: backup_user == "root"

- name: save the public keys (no root user)
  fetch:
    src: /home/{{ backup_user }}/.ssh/id_rsa.pub
    dest: keys/users/backup/
    flat: yes
  when: backup_user != "root"
