---
- name: create the directory of the data at '{{ load_balancer_configuration_file_directory }}'
  file:
    path: "{{ load_balancer_configuration_file_directory }}"
    state: directory
    owner: "{{ load_balancer_files_owner }}"
    group: "{{ load_balancer_files_group }}"

- name: copy the configuration file from '{{ load_balancer_configuration_file_src }}' to '{{ load_balancer_configuration_file_dest }}'
  copy:
    src: "{{ load_balancer_configuration_file_src }}"
    dest: "{{ load_balancer_configuration_file_dest }}"
    owner: "{{ load_balancer_files_owner }}"
    group: "{{ load_balancer_files_group }}"
