---
- name: start the docker container '{{ load_balancer_container_name }}'
  docker_container:
    image: "{{ load_balancer_image_name }}"
    name: "{{ load_balancer_container_name }}"
    detach: true
    restart_policy: "always"
    exposed_ports:
    - 80
    - 8080
    - 443
    published_ports:
    - 80:80
    - 8080:8080
    - 443:443
    volumes:
    - "{{ load_balancer_configuration_file_dest }}:/etc/nginx/nginx.conf:ro"
    - "{{ load_balancer_certs_directory_path }}:/etc/nginx/certs:ro"
    networks:
    - name: proxy
    labels:
      role: load-balancer

- name: reload the load-balancer configuration
  command: "docker restart {{ load_balancer_container_name }}"