---
- name: allow TCP connections for prometheus
  iptables:
    table: filter
    chain: INPUT
    protocol: tcp
    destination_port: "{{ monitoring_prometheus_port }}"
    jump: ACCEPT
    comment: "from ansible"

- name: allow TCP connections for grafana
  iptables:
    table: filter
    chain: INPUT
    protocol: tcp
    destination_port: "{{ monitoring_grafana_port }}"
    jump: ACCEPT
    comment: "from ansible"