---
- name: execute the pre-generate action '{{ certbot_pre_action_generate }}'
  command: "{{ certbot_pre_action_generate }}"
  ignore_errors: yes
  when: certbot_pre_action_generate != ""

- name: generate the certificates for the domains '{{ certbot_domains | join(', ') }}'
  command: certbot certonly --standalone --expand --agree-tos -n -m {{ certbot_email_address }} -d {{ certbot_domains | join(' -d ') }}

- name: create the '{{ certbot_certs_path }}' directory
  file:
    path: "{{ certbot_certs_path }}"
    state: directory
    mode: 0775
  when: certbot_certs_path is defined

- name: get the contents of the directory '{{ certbot_original_certs_path }}/{{ certbot_domains[0] }}{{ certbot_certs_path_prefix }}'
  command: ls {{ certbot_original_certs_path }}/{{ certbot_domains[0] }}{{ certbot_certs_path_prefix }}
  register: cert_files
  when: certbot_certs_path is defined
  changed_when: False

- name: copy the certificate files from the directory '{{ certbot_original_certs_path }}/{{ certbot_domains[0] }}{{ certbot_certs_path_prefix }}' to the directory '{{ certbot_certs_path }}'
  command: "cp {{ certbot_original_certs_path }}/{{ certbot_domains[0] }}{{ certbot_certs_path_prefix }}/{{ item }} {{ certbot_certs_path }}/{{ item }}"
  with_items: "{{ cert_files.stdout_lines }}"
  when: certbot_certs_path is defined

- name: execute the post-generate action '{{ certbot_post_action_generate }}'
  command: "{{ certbot_post_action_generate }}"
  ignore_errors: yes
  when: certbot_post_action_generate != ""
