---
- name: allow HTTP and HTTPS daemon connections
  iptables:
    table: filter
    chain: INPUT
    protocol: tcp
    destination_port: "{{ item }}"
    jump: ACCEPT
    comment: "from ansible"
  with_items:
  - "80"
  - "443"
