---
docker_swarm_manager_ip: 127.0.0.1
docker_swarm_manager_port: 2377
docker_swarm_is_main_manager: 0
docker_swarm_is_manager: 0
docker_tcp_ports:
  - "2377"
  - "7946"
  - "4789"
docker_udp_ports:
  - "7946"
  - "4789"
