---
# Tasks to install the docker package.
- name: delete the old 'docker.list' file
  file:
    path: /etc/apt/sources.list.d/docker.list
    state: absent

- name: ensure that the older repositories are uninstalled
  apt:
    pkg: "{{ docker_older_repositories }}"
    state: absent
    purge: yes
    update_cache: yes

- name: ensure that the latest dependent packages are installed
  apt:
    pkg: "{{ docker_dependencies }}"
    state: latest
    update_cache: yes

- name: add GPG key from '{{ docker_apt_key_server }}'
  apt_key:
    url: "{{ docker_apt_key_server }}"
    id: "{{ docker_apt_key_id }}"
    
- name: get the release name
  command: lsb_release -cs
  register: lsbrelease

- name: add the APT repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ lsbrelease.stdout }} stable"
    update_cache: yes

- name: ensure that the latest '{{ docker_pkg_name }}' package is installed
  apt:
    pkg: "{{ docker_pkg_name }}"
    state: latest
    update_cache: yes

# Install docker-compose
- name: get the OS name
  command: uname -s
  register: unames

- name: get the OS version
  command: uname -m
  register: unamem

- name: download the latest 'docker-compose' version
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ unames.stdout }}-{{ unamem.stdout }}"
    dest: "{{ docker_compose_path }}"
    owner: root
    group: root
    mode: "0755"
    force: yes

# Start the docker daemon.
- name: restart docker
  service:
    name: "{{ docker_service_name }}"
    state: restarted
    enabled: yes
