---
- name: add the '{{ docker_group }}' group
  group:
    name: "{{ docker_group }}"
    gid: "{{ docker_group_id }}"

- name: add the '{{ docker_user }}' user
  user:
    name: "{{ docker_user }}"
    uid: "{{ docker_user_id }}"
    group: "{{ docker_group }}"
    generate_ssh_key: "{{ docker_user_generate_ssh_key }}"
    ssh_key_bits: "{{ docker_user_ssh_key_bits }}"
    ssh_key_comment: "{{ docker_user_ssh_key_comment }}"

- name: save the '{{ docker_user }}' user public key to '{{ docker_user_ssh_key_dest }}.pub'
  fetch:
    src: /home/{{ docker_user }}/.ssh/id_rsa.pub
    dest: keys/remote/{{ docker_user_ssh_key_dest }}.pub
    flat: yes

- name: create the data directory
  file:
    path: "{{ docker_data_directory }}"
    state: directory
    mode: 0775
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
