---
- name: allow TCP connections
  iptables:
    table: filter
    chain: INPUT
    protocol: tcp
    destination_port: "{{ docker_registry_port }}"
    jump: ACCEPT
    comment: "from ansible"
    
