---
- name: ensure that the latest '{{ paranoid_fail2ban_pkg_name }}' package is installed
  apt:
    pkg: "{{ paranoid_fail2ban_pkg_name }}"
    state: latest
  notify: restart fail2ban
  when: paranoid_fail2ban

- name: copy '{{ paranoid_fail2ban_pkg_name }}' configuration file
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    force: yes
    backup: yes
  notify: restart fail2ban
  when: paranoid_fail2ban
